name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  smoke-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Start dev server
        run: npm run dev --if-present &

      - name: Wait for server
        run: npx wait-on http://localhost:3000/api/health

      - name: Run smoke tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          RECALL_THRESHOLD: ${{ secrets.RECALL_THRESHOLD }}
          CHAT_MODEL: gpt-4o-mini
        run: ./scripts/smoke-test.sh
