name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Start dev server
        run: npm run dev &
      
      - name: Wait for server
        run: npx wait-on http://localhost:3000/api/health

      - name: Smoke tests (positive & negative)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          RECALL_THRESHOLD: 0.75
          CHAT_MODEL: gpt-4o-mini
        run: |
          ./scripts/smoke-test.sh
          # negative test: expect 400
          status=$(curl -s -o /dev/null -w "%{http_code}" -X POST http://localhost:3000/api/shrink \
            -H "Content-Type: application/json" \
            -d '{}')
          if [ "$status" -ne 400 ]; then
            echo "Expected 400 for missing prompt, got $status"
            exit 1
          fi
